name: Update Contributors

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update_contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update CONTRIBUTORS.md
        run: |
          echo '## Contributors' > CONTRIBUTORS.md
          echo 'We appreciate the contributions from the following individuals. Here are their profile pictures:' >> CONTRIBUTORS.md
          echo '|' Contributor | Profile Picture |' >> CONTRIBUTORS.md
          echo '|-------------|-----------------|' >> CONTRIBUTORS.md
          
          # Loop through contributors
          for contributor in $(git log --format='%aN' | sort -u); do
            # Get the profile picture URL from GitHub API (update the URL pattern if needed)
            avatar_url=$(curl -s "https://api.github.com/users/${contributor}" | jq -r .avatar_url)
            echo "| $contributor | ![$contributor]($avatar_url) |" >> CONTRIBUTORS.md
          done

      - name: Commit changes
        run: |
          git config --local user.email "your-email@example.com"
          git config --local user.name "GitHub Action"
          git add CONTRIBUTORS.md
          git commit -m "Update CONTRIBUTORS.md" || echo "No changes to commit"
          git push
