name: LuaLint

# Run on pushes and pull requests
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install luarocks and luacheck locally
      - name: Install luarocks and luacheck locally
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          luarocks install --local luacheck
          # Export LuaRocks path to the environment
          echo "$(luarocks path --bin)" >> $GITHUB_ENV
          echo "$(luarocks path)" >> $GITHUB_ENV

      # Step 3: Add local luarocks bin to PATH
      - name: Add luarocks bin to PATH
        run: |
          export PATH=$HOME/.luarocks/bin:$PATH
          luarocks path
          luacheck --version

      # Step 4: Run luacheck on Lua files
      - name: Run LuaLint (luacheck)
        run: |
          export PATH=$HOME/.luarocks/bin:$PATH
          luacheck .
