name: Push to GitLab

on:
  push:
    branches:
      - master
  pull_request:
    types: [merged]

jobs:
  push-to-gitlab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab ${{ secrets.GITLAB_REPO }}
          git push gitlab master --force --set-upstream
