name: Check Code Style

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Stylua
        run: |
          sudo apt-get update
          sudo apt-get install -y stylua

      - name: Check code style
        run: |
          stylua --check .
