name: Update Changelog

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - merged

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies (if needed)
        run: npm install

      - name: Generate Changelog
        run: |
          echo "## Changelog" > CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "### $(date +'%Y-%m-%d')" >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          git log --pretty=format:'* %s - %an' --no-merges HEAD..HEAD~1 >> CHANGELOG.md
          echo "" >> CHANGELOG.md

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push origin main
